export function mapPpobProduct(product: any) {
  return {
    uuid: product.uuid,
    provider: product.provider,
    provider_label: product.provider === 'rajabiller' ? 'RajaBiller' : 'Digiflazz',
    provider_product_code: product.providerProductCode,
    product_name: product.productName,
    brand: product.brand,
    category: product.category,
    type: product.type,
    seller_name: product.sellerName,
    base_price: Number(product.basePrice),
    admin_fee: Number(product.adminFee),
    selling_price: Number(product.sellingPrice),
    digiflazz_type: product.digiflazzType,
    buyer_product_status: product.buyerProductStatus,
    seller_product_status: product.sellerProductStatus,
    unlimited_stock: product.unlimitedStock,
    stock: product.stock,
    multi: product.multi,
    start_cut_off: product.startCutOff,
    end_cut_off: product.endCutOff,
    desc: product.desc,
    is_active: product.isActive,
    provider_metadata: product.providerMetadata,
    created_at: product.createdAt,
    updated_at: product.updatedAt,
  };
}
